<a target="_blank" href="https://colab.research.google.com/github/victorlymarev/pandas/blob/main/notebooks/03-create-tables.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Создание таблиц
#### [Ссылка на видео](https://youtu.be/B02VfvdXJfA)

In [1]:
import pandas as pd
import numpy as np

## Создание объекта Series

### На основе одного значения

In [2]:
pd.Series(1)

0    1
dtype: int64

In [3]:
pd.Series('pandas')

0    pandas
dtype: object

### На основе списка

In [4]:
['Аня', 'Маша', 'Вася', 'Катя', 'Аня']

['Аня', 'Маша', 'Вася', 'Катя', 'Аня']

In [5]:
pd.Series(['Аня', 'Маша', 'Вася', 'Катя', 'Аня'])

0     Аня
1    Маша
2    Вася
3    Катя
4     Аня
dtype: object

In [6]:
pd.Series(['Аня', 'Маша', 'Вася', 'Катя', 'Аня']).value_counts()

Аня     2
Маша    1
Вася    1
Катя    1
Name: count, dtype: int64

### На основе словаря

In [7]:
pd.Series({3:"Катя", 9:"Света", 34: "Паша"})

3      Катя
9     Света
34     Паша
dtype: object

## Создание датафреймов

### На основе словаря

In [8]:
people_dict = {
    'Имя': ['Екатерина', 'Евгений', 'Андрей', 'Виктория', 'Анастасия', 'Данил'],
    
    'Фамилия': [pd.NA, 'Бубликов', 'Васильев', 'Леонова', 'Долгова',
                'Новиков'],
    
    'Дата рождения': pd.to_datetime(['1992-06-25', '1995-09-09', '2000-02-29',
                                     '1999-06-15', '2003-04-06', '1995-06-03']),
    
    'Количество детей': 0,
    
    'Дата увольнения': pd.Timestamp('12-06-2023')
}

In [9]:
pd.DataFrame(people_dict)

Имя   Фамилия Дата рождения  Количество детей Дата увольнения
0  Екатерина      <NA>    1992-06-25                 0      2023-12-06
1    Евгений  Бубликов    1995-09-09                 0      2023-12-06
2     Андрей  Васильев    2000-02-29                 0      2023-12-06
3   Виктория   Леонова    1999-06-15                 0      2023-12-06
4  Анастасия   Долгова    2003-04-06                 0      2023-12-06
5      Данил   Новиков    1995-06-03                 0      2023-12-06

## Функции для создания периодических чисел или дат

### np.arange

Генерирует целые числа

#### Синтаксис

1. np.arange(первое число в массиве, последнее число в массиве невключительно, шаг (по умолчанию равен 1))
2. np.arange(последнее число в массиве невключительно)

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(2, 5)

array([2, 3, 4])

In [12]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [13]:
np.arange(-50, 10, 1.5)

array([-50. , -48.5, -47. , -45.5, -44. , -42.5, -41. , -39.5, -38. ,
       -36.5, -35. , -33.5, -32. , -30.5, -29. , -27.5, -26. , -24.5,
       -23. , -21.5, -20. , -18.5, -17. , -15.5, -14. , -12.5, -11. ,
        -9.5,  -8. ,  -6.5,  -5. ,  -3.5,  -2. ,  -0.5,   1. ,   2.5,
         4. ,   5.5,   7. ,   8.5])

In [14]:
from random import randint

In [15]:
np.arange(randint(1, 10))

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
np.arange(100, 0, -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

### np.linspace

Делит отрезок на равные части

#### Синтаксис:

np.linspace(нначало отрезка, конц отрезка, число точек на отрезке)

In [17]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(5, 6, 8)

array([5.        , 5.14285714, 5.28571429, 5.42857143, 5.57142857,
       5.71428571, 5.85714286, 6.        ])

### pd.date_range(start, end, periods, freq)

__start__ - начало периода генерации дат

__end__ - конец периода генерации дат

__periods__ - количество дат для генерации

__freq__ - период, с которым даты будут генерироваться

In [19]:
pd.date_range('2020-09-06', '2023-05-18', periods=15)

DatetimeIndex([          '2020-09-06 00:00:00',
               '2020-11-15 06:51:25.714285714',
               '2021-01-24 13:42:51.428571428',
               '2021-04-04 20:34:17.142857144',
               '2021-06-14 03:25:42.857142856',
               '2021-08-23 10:17:08.571428568',
               '2021-11-01 17:08:34.285714288',
                         '2022-01-11 00:00:00',
               '2022-03-22 06:51:25.714285712',
               '2022-05-31 13:42:51.428571424',
               '2022-08-09 20:34:17.142857136',
               '2022-10-19 03:25:42.857142856',
               '2022-12-28 10:17:08.571428576',
               '2023-03-08 17:08:34.285714288',
                         '2023-05-18 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [20]:
pd.date_range('2020-09-06', '2023-05-18', periods=15).normalize()

DatetimeIndex(['2020-09-06', '2020-11-15', '2021-01-24', '2021-04-04',
               '2021-06-14', '2021-08-23', '2021-11-01', '2022-01-11',
               '2022-03-22', '2022-05-31', '2022-08-09', '2022-10-19',
               '2022-12-28', '2023-03-08', '2023-05-18'],
              dtype='datetime64[ns]', freq=None)

In [21]:
pd.date_range('2020-09-06 15:00', '2023-05-18', freq='2d 6h')

DatetimeIndex(['2020-09-06 15:00:00', '2020-09-08 21:00:00',
               '2020-09-11 03:00:00', '2020-09-13 09:00:00',
               '2020-09-15 15:00:00', '2020-09-17 21:00:00',
               '2020-09-20 03:00:00', '2020-09-22 09:00:00',
               '2020-09-24 15:00:00', '2020-09-26 21:00:00',
               ...
               '2023-04-27 15:00:00', '2023-04-29 21:00:00',
               '2023-05-02 03:00:00', '2023-05-04 09:00:00',
               '2023-05-06 15:00:00', '2023-05-08 21:00:00',
               '2023-05-11 03:00:00', '2023-05-13 09:00:00',
               '2023-05-15 15:00:00', '2023-05-17 21:00:00'],
              dtype='datetime64[ns]', length=438, freq='54h')

In [22]:
pd.date_range('2020-09-06 15:00', freq='2d 6h', periods=15)

DatetimeIndex(['2020-09-06 15:00:00', '2020-09-08 21:00:00',
               '2020-09-11 03:00:00', '2020-09-13 09:00:00',
               '2020-09-15 15:00:00', '2020-09-17 21:00:00',
               '2020-09-20 03:00:00', '2020-09-22 09:00:00',
               '2020-09-24 15:00:00', '2020-09-26 21:00:00',
               '2020-09-29 03:00:00', '2020-10-01 09:00:00',
               '2020-10-03 15:00:00', '2020-10-05 21:00:00',
               '2020-10-08 03:00:00'],
              dtype='datetime64[ns]', freq='54h')

### Список всех сокращений (регистр их записи не важен)

| Сокращение   | Расшифровка                              | Сокращение   | Расшифровка                    |
|:-------------|:-----------------------------------------|:-------------|:-------------------------------|
| B            | Последний рабочий день в неделе          | QS           | Начало квартала                |
| C            | Пользовательский последний день в неделе | BQS          | Первый рабочий день квартала   |
| D            | День                                     | A, Y         | Конец года                     |
| W            | Неделя                                   | BA, BY       | Последний рабочий день в году  |
| M            | Конец месяца                             | AS, YS       | Начало года                    |
| SM           | 15 число месяца                          | BAS, BYS     | Первый рабочий день в году     |
| BM           | Последний рабочий день в месяце          | BH           | Рабочий час (от 9:00 до 17:00) |
| CBM          | Пользовательский конец месяца            | H            | Час                            |
| MS           | Первое число месяца                      | T, min       | Минута                         |
| SMS          | 1 и 15 число месяца                      | S            | Секунда                        |
| BMS          | Первый рабочий день месяца               | L, ms        | Миллисекунда                   |
| CBMS         | Пользовательский первый день месяца      | U, us        | Микросекунда                   |
| Q            | Конец квартала                           | N            | Наносекунда                    |
| BQ           | Последний рабочий день квартала          

In [23]:
pd.date_range('2020-08-06 15:00', '2023-05-18', freq='M')

/tmp/ipykernel_6675/587386093.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range('2020-08-06 15:00', '2023-05-18', freq='M')


DatetimeIndex(['2020-08-31 15:00:00', '2020-09-30 15:00:00',
               '2020-10-31 15:00:00', '2020-11-30 15:00:00',
               '2020-12-31 15:00:00', '2021-01-31 15:00:00',
               '2021-02-28 15:00:00', '2021-03-31 15:00:00',
               '2021-04-30 15:00:00', '2021-05-31 15:00:00',
               '2021-06-30 15:00:00', '2021-07-31 15:00:00',
               '2021-08-31 15:00:00', '2021-09-30 15:00:00',
               '2021-10-31 15:00:00', '2021-11-30 15:00:00',
               '2021-12-31 15:00:00', '2022-01-31 15:00:00',
               '2022-02-28 15:00:00', '2022-03-31 15:00:00',
               '2022-04-30 15:00:00', '2022-05-31 15:00:00',
               '2022-06-30 15:00:00', '2022-07-31 15:00:00',
               '2022-08-31 15:00:00', '2022-09-30 15:00:00',
               '2022-10-31 15:00:00', '2022-11-30 15:00:00',
               '2022-12-31 15:00:00', '2023-01-31 15:00:00',
               '2023-02-28 15:00:00', '2023-03-31 15:00:00',
               '2023-04-

In [24]:
pd.date_range('2020-08-06 15:00', '2023-05-18', freq='MS')

DatetimeIndex(['2020-09-01 15:00:00', '2020-10-01 15:00:00',
               '2020-11-01 15:00:00', '2020-12-01 15:00:00',
               '2021-01-01 15:00:00', '2021-02-01 15:00:00',
               '2021-03-01 15:00:00', '2021-04-01 15:00:00',
               '2021-05-01 15:00:00', '2021-06-01 15:00:00',
               '2021-07-01 15:00:00', '2021-08-01 15:00:00',
               '2021-09-01 15:00:00', '2021-10-01 15:00:00',
               '2021-11-01 15:00:00', '2021-12-01 15:00:00',
               '2022-01-01 15:00:00', '2022-02-01 15:00:00',
               '2022-03-01 15:00:00', '2022-04-01 15:00:00',
               '2022-05-01 15:00:00', '2022-06-01 15:00:00',
               '2022-07-01 15:00:00', '2022-08-01 15:00:00',
               '2022-09-01 15:00:00', '2022-10-01 15:00:00',
               '2022-11-01 15:00:00', '2022-12-01 15:00:00',
               '2023-01-01 15:00:00', '2023-02-01 15:00:00',
               '2023-03-01 15:00:00', '2023-04-01 15:00:00',
               '2023-05-

### Метод shift

In [25]:
pd.date_range('2020-08-06 15:00', '2023-05-18', freq='MS').shift(5, 'd')

DatetimeIndex(['2020-09-06 15:00:00', '2020-10-06 15:00:00',
               '2020-11-06 15:00:00', '2020-12-06 15:00:00',
               '2021-01-06 15:00:00', '2021-02-06 15:00:00',
               '2021-03-06 15:00:00', '2021-04-06 15:00:00',
               '2021-05-06 15:00:00', '2021-06-06 15:00:00',
               '2021-07-06 15:00:00', '2021-08-06 15:00:00',
               '2021-09-06 15:00:00', '2021-10-06 15:00:00',
               '2021-11-06 15:00:00', '2021-12-06 15:00:00',
               '2022-01-06 15:00:00', '2022-02-06 15:00:00',
               '2022-03-06 15:00:00', '2022-04-06 15:00:00',
               '2022-05-06 15:00:00', '2022-06-06 15:00:00',
               '2022-07-06 15:00:00', '2022-08-06 15:00:00',
               '2022-09-06 15:00:00', '2022-10-06 15:00:00',
               '2022-11-06 15:00:00', '2022-12-06 15:00:00',
               '2023-01-06 15:00:00', '2023-02-06 15:00:00',
               '2023-03-06 15:00:00', '2023-04-06 15:00:00',
               '2023-05-

In [26]:
(pd.date_range('2020-08-06 15:00', '2023-05-18', freq='Y')
    .shift(5, 'M')
    .shift(-2, 'h')
)

/tmp/ipykernel_6675/3862665698.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  (pd.date_range('2020-08-06 15:00', '2023-05-18', freq='Y')
/tmp/ipykernel_6675/3862665698.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .shift(5, 'M')


DatetimeIndex(['2021-05-31 13:00:00', '2022-05-31 13:00:00',
               '2023-05-31 13:00:00'],
              dtype='datetime64[ns]', freq=None)

###  Атрибут shape

In [27]:
pd.DataFrame(people_dict)

Имя   Фамилия Дата рождения  Количество детей Дата увольнения
0  Екатерина      <NA>    1992-06-25                 0      2023-12-06
1    Евгений  Бубликов    1995-09-09                 0      2023-12-06
2     Андрей  Васильев    2000-02-29                 0      2023-12-06
3   Виктория   Леонова    1999-06-15                 0      2023-12-06
4  Анастасия   Долгова    2003-04-06                 0      2023-12-06
5      Данил   Новиков    1995-06-03                 0      2023-12-06

In [28]:
pd.DataFrame(people_dict).shape

(6, 5)

In [29]:
pd.DataFrame(people_dict).shape[0]

6

In [30]:
len(pd.DataFrame(people_dict))

6

# Задания

#### Описание таблиц лежит [здесь](https://github.com/victorlymarev/pandas/tree/main/tables#%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86)

Некоторые таблицы занимают много памяти, поэтому каждые 5-10 заданий лучше перезапускайте ноутбук.

В формулировке некоторых заданий может содержаться вариативность. Если у вас есть сомнения, что требуется в задании, попробуйте решить несколько вариантов. Если вы не понимаете задание, можете написать об этом в комментариях под видео.

В большинстве случаев внешний вид итоговой таблицы не определен. Выведите на экран наиболее адекватный вариант. То есть таблицу, из которой можно будет сделать выводы.

Курс пока находится в разработке. Вы можете помочь другим людям добавив свое решение [сюда](https://docs.google.com/forms/d/1HYTBz_KfssY3Jps2dC3n0YnEqa6WBb5OIhLo1d32Xzw/edit).

Посмотреть решения других людей можно [здесь](https://docs.google.com/spreadsheets/d/1pMDYO-9UneLbPPnEuQ2shig0TOJdQTU-zipifyAnZMk/edit?resourcekey#gid=1998648012)

### Задание 1
Создайте объект Series, в котором будут лежать последовательно имена Аня, Наташа, Таня, Оля, Настя

In [31]:
import pandas as pd

pd.Series(['Аня', 'Наташа', 'Таня', 'Оля', 'Настя'])

0       Аня
1    Наташа
2      Таня
3       Оля
4     Настя
dtype: object

### Задание 2
Создавать объекты Series можно на основе словарей. В этом случае ключ пойдет в индекс, а значение в тело колонки.

In [32]:
import pandas as pd

height = {'Кирилл': 178, 'Андрей': 189, 'Тимур': 159, 'Ярослав': 190}
pd.Series(height)

Кирилл     178
Андрей     189
Тимур      159
Ярослав    190
dtype: int64

Создайте на основе словаря объект Series. В индексе словаря пусть лежат имена Никита, Артур, Паша, а в значениях колонки номера телефонов 123456, 654321, 123321. 

In [33]:
pd.Series({'Никита':123456, "Артур":654321, "Вася":123321})

Никита    123456
Артур     654321
Вася      123321
dtype: int64

### Задание 3
Создайте таблицу, состоящую из двух колонок. В перовой колонке должны быть имена Саша, Маша, Лера, Руслан. Во второй колонке пусть лежат фамилии Сидоров, Петрова, Иванова, Уткин

In [34]:
import pandas as pd

pd.DataFrame(
    {
        "Имя": ["Саша", "Маша", "Лера", "Руслан"],
        "Фамилии": ["Сидоров", "Петрова", "Иванова", "Уткин"],
    }
)

Имя  Фамилии
0    Саша  Сидоров
1    Маша  Петрова
2    Лера  Иванова
3  Руслан    Уткин

### Задание 4

В таблице marks_6d лежат оценки школьников в классе 6Д. Какое количество школьников в классе?

In [35]:
import os
import pandas as pd
path_marks_6d = '../tables/оценки 6Д.csv' if os.path.exists('../tables/оценки 6Д.csv') else 'https://drive.google.com/uc?id=1aMvwur2zrISbVPRo86qWgbHPEpw5km0n'
marks_6d = pd.read_csv(path_marks_6d)
marks_6d

ФИО      Пол  Математика  Русский язык  \
0       Большакова Ольга Захаровна  женский           4             5   
1         Михайлов Артем Артемович  мужской           5             5   
2       Афанасьев Леонид Артурович  мужской           4             4   
3         Козлов Николай Артёмович  мужской           3             4   
4         Крылова Марина Сергеевна  женский           5             5   
5        Елизаров Денис Кириллович  мужской           3             3   
6         Рыбаков Андрей Захарович  мужской           4             5   
7   Мартынова Елизаваета Фёдоровна  женский           3             3   
8         Лазарева Мария Артемовна  женский           5             5   
9          Фадеева Анна Руслановна  женский           4             5   
10      Фомина Мария Александровна  женский           3             3   
11       Постников Фёдор Артёмович  мужской           3             3   
12     Самойлова Надежда Антоновна  женский           4             3   
13    Гаврилов Александр Борисович  мужской           4             3   
14   Постников Родион Владимирович  мужской           5             3   
15    Бычкова Александра Борисовна  женский           5             4   
16        Кулешов Семен Богданович  мужской           4             4   
17    Павловскиая Алена Данииловна  женский           3             4   
18            Лапин Юрий Тимурович  мужской           4             4   
19       Курочкин Андрей Семенович  мужской           4             5   

    Литература  Физика  История  Физическая культура  
0            5       4        5                    5  
1            5       4        4                    4  
2            3       4        3                    5  
3            4       4        3                    5  
4            4       4        4                    5  
5            3       3        3                    5  
6            5       3        5                    5  
7            3       4        3                    4  
8            4       5        5                    5  
9            4       5        5                    3  
10           3       4        4                    5  
11           3       3        3                    5  
12           4       4        3                    5  
13           4       3        3                    5  
14           3       5        3                    5  
15           3       5        3                    5  
16           4       4        4                    4  
17           5       4        3                    5  
18           4       5        3                    5  
19           5       4        5                    5

In [45]:
marks_6d['ФИО'].nunique()

20

### Задание 5

Создайте набор точек от 1 до 150 с интервалом 2

In [46]:
import numpy as np

np.arange(1, 150, 2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149])

### Задание 6

Создайте набор точек от 0 до 15 включительно с интервалом 1.5

In [47]:
import numpy as np

np.arange(0, 15, 1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

### Задание 7

На отрезке от 100 до 150 создайте 80 равноудаленных друг от друга точек

In [48]:
import numpy as np

np.linspace(100, 150, 80)

array([100.        , 100.63291139, 101.26582278, 101.89873418,
       102.53164557, 103.16455696, 103.79746835, 104.43037975,
       105.06329114, 105.69620253, 106.32911392, 106.96202532,
       107.59493671, 108.2278481 , 108.86075949, 109.49367089,
       110.12658228, 110.75949367, 111.39240506, 112.02531646,
       112.65822785, 113.29113924, 113.92405063, 114.55696203,
       115.18987342, 115.82278481, 116.4556962 , 117.08860759,
       117.72151899, 118.35443038, 118.98734177, 119.62025316,
       120.25316456, 120.88607595, 121.51898734, 122.15189873,
       122.78481013, 123.41772152, 124.05063291, 124.6835443 ,
       125.3164557 , 125.94936709, 126.58227848, 127.21518987,
       127.84810127, 128.48101266, 129.11392405, 129.74683544,
       130.37974684, 131.01265823, 131.64556962, 132.27848101,
       132.91139241, 133.5443038 , 134.17721519, 134.81012658,
       135.44303797, 136.07594937, 136.70886076, 137.34177215,
       137.97468354, 138.60759494, 139.24050633, 139.87

### Задание 8

Создайте набор дат с 18 марта 1999 года до 28 февраля 2021 года с частотой в 1 день

In [49]:
import pandas as pd

In [51]:
pd.date_range('18.03.1999', '28.02.2021', freq='D')

DatetimeIndex(['1999-03-18', '1999-03-19', '1999-03-20', '1999-03-21',
               '1999-03-22', '1999-03-23', '1999-03-24', '1999-03-25',
               '1999-03-26', '1999-03-27',
               ...
               '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22',
               '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26',
               '2021-02-27', '2021-02-28'],
              dtype='datetime64[ns]', length=8019, freq='D')

### Задание 9

Создайте набор дат с даты вашего рождения и до сегодняшнего дня с частотой в 1 день. При помощи функции len посчитайте длинну массива

In [52]:
import pandas as pd


DatetimeIndex(['1996-07-26', '1996-07-27', '1996-07-28', '1996-07-29',
               '1996-07-30', '1996-07-31', '1996-08-01', '1996-08-02',
               '1996-08-03', '1996-08-04',
               ...
               '2024-10-24', '2024-10-25', '2024-10-26', '2024-10-27',
               '2024-10-28', '2024-10-29', '2024-10-30', '2024-10-31',
               '2024-11-01', '2024-11-02'],
              dtype='datetime64[ns]', length=10327, freq='D')

### Задание 10

Создайте набор дат с 18 марта 2009 года до 28 февраля 2021 года с частотой в 4 дня 19 часов

In [54]:
import pandas as pd
pd.date_range('18.03.2009', '28.02.2021', freq='4d 19h')

DatetimeIndex(['2009-03-18 00:00:00', '2009-03-22 19:00:00',
               '2009-03-27 14:00:00', '2009-04-01 09:00:00',
               '2009-04-06 04:00:00', '2009-04-10 23:00:00',
               '2009-04-15 18:00:00', '2009-04-20 13:00:00',
               '2009-04-25 08:00:00', '2009-04-30 03:00:00',
               ...
               '2021-01-11 07:00:00', '2021-01-16 02:00:00',
               '2021-01-20 21:00:00', '2021-01-25 16:00:00',
               '2021-01-30 11:00:00', '2021-02-04 06:00:00',
               '2021-02-09 01:00:00', '2021-02-13 20:00:00',
               '2021-02-18 15:00:00', '2021-02-23 10:00:00'],
              dtype='datetime64[ns]', length=911, freq='115h')

### Задание 11

Создайте набор дат с 18 марта 2009 года до 18 февраля 2021 года с частотой в 1 месяц

In [61]:
import pandas as pd

pd.date_range('18.03.2009','18.03.2021', freq='MS').shift(18, 'd')

DatetimeIndex(['2009-04-19', '2009-05-19', '2009-06-19', '2009-07-19',
               '2009-08-19', '2009-09-19', '2009-10-19', '2009-11-19',
               '2009-12-19', '2010-01-19',
               ...
               '2020-06-19', '2020-07-19', '2020-08-19', '2020-09-19',
               '2020-10-19', '2020-11-19', '2020-12-19', '2021-01-19',
               '2021-02-19', '2021-03-19'],
              dtype='datetime64[ns]', length=144, freq=None)

### Задание 12

Создайте 8 дат с частотой в 3 часа начиная от 9 часов утра 21 декабря 1999 года

In [63]:
import pandas as pd

pd.date_range('21.12.1999', freq='3 h', periods=8).shift(9, 'h')

DatetimeIndex(['1999-12-21 09:00:00', '1999-12-21 12:00:00',
               '1999-12-21 15:00:00', '1999-12-21 18:00:00',
               '1999-12-21 21:00:00', '1999-12-22 00:00:00',
               '1999-12-22 03:00:00', '1999-12-22 06:00:00'],
              dtype='datetime64[ns]', freq='3h')